In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ast
import datetime

In [9]:
df = pd.read_csv('final_data_downloaded.csv')
df

,Unnamed: 0,Port_IDs,activeBuy,positionSide,side,quantityAsset,symbol,realizedProfitAsset,qty,feeAsset,baseAsset,realizedProfit,quantity,fee,price,time,price_quantity
0,0,3925368433214965504,True,LONG,BUY,USDT,SOLUSDT,USDT,15.0,USDT,SOL,0.0,1988.055000,-0.994027,132.537000,2024-06-20 16:07:36,1988.055000
1,1,3925368433214965504,False,LONG,BUY,USDT,DOGEUSDT,USDT,11484.0,USDT,DOGE,0.0,1398.980880,-0.279796,0.121820,2024-06-20 16:06:58,1398.980880
2,2,3925368433214965504,False,LONG,BUY,USDT,DOGEUSDT,USDT,1621.0,USDT,DOGE,0.0,197.470220,-0.039494,0.121820,2024-06-20 16:06:58,197.470220
3,3,3925368433214965504,True,LONG,BUY,USDT,DOGEUSDT,USDT,136.0,USDT,DOGE,0.0,16.567520,-0.008284,0.121820,2024-06-20 16:06:56,16.567520
4,4,3925368433214965504,True,LONG,BUY,USDT,DOGEUSDT,USDT,757.0,USDT,DOGE,0.0,92.217740,-0.046109,0.121820,2024-06-20 16:06:56,92.217740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211272,211272,3768170840939476993,False,BOTH,SELL,USDT,JASMYUSDT,USDT,1394.0,USDT,JASMY,0.0,50.139392,-0.025070,0.035968,2024-06-16 14:57:55,50.139392
211273,211273,3768170840939476993,False,BOTH,SELL,USDT,JASMYUSDT,USDT,459.0,USDT,JASMY,0.0,16.509312,-0.008255,0.035968,2024-06-16 14:57:55,16.509312
211274,211274,3768170840939476993,False,BOTH,SELL,USDT,JASMYUSDT,USDT,1754.0,USDT,JASMY,0.0,63.089626,-0.031545,0.035969,2024-06-16 14:57:55,63.089626
211275,211275,3768170840939476993,False,BOTH,SELL,USDT,JASMYUSDT,USDT,1774.0,USDT,JASMY,0.0,63.809006,-0.031905,0.035969,2024-06-16 14:57:55,63.809006
211276,211276,3768170840939476993,False,BOTH,SELL,USDT,JASMYUSDT,USDT,279.0,USDT,JASMY,0.0,10.036188,-0.005018,0.035972,2024-06-16 14:57:55,10.036188

In [10]:
df.head()

,Unnamed: 0,Port_IDs,activeBuy,positionSide,side,quantityAsset,symbol,realizedProfitAsset,qty,feeAsset,baseAsset,realizedProfit,quantity,fee,price,time,price_quantity
0,0,3925368433214965504,True,LONG,BUY,USDT,SOLUSDT,USDT,15.0,USDT,SOL,0.0,1988.05500,-0.994027,132.53700,2024-06-20 16:07:36,1988.05500
1,1,3925368433214965504,False,LONG,BUY,USDT,DOGEUSDT,USDT,11484.0,USDT,DOGE,0.0,1398.98088,-0.279796,0.12182,2024-06-20 16:06:58,1398.98088
2,2,3925368433214965504,False,LONG,BUY,USDT,DOGEUSDT,USDT,1621.0,USDT,DOGE,0.0,197.47022,-0.039494,0.12182,2024-06-20 16:06:58,197.47022
3,3,3925368433214965504,True,LONG,BUY,USDT,DOGEUSDT,USDT,136.0,USDT,DOGE,0.0,16.56752,-0.008284,0.12182,2024-06-20 16:06:56,16.56752
4,4,3925368433214965504,True,LONG,BUY,USDT,DOGEUSDT,USDT,757.0,USDT,DOGE,0.0,92.21774,-0.046109,0.12182,2024-06-20 16:06:56,92.21774

In [12]:
final_stats = df.describe(include='all')
final_stats

,Unnamed: 0,Port_IDs,activeBuy,positionSide,side,quantityAsset,symbol,realizedProfitAsset,qty,feeAsset,baseAsset,realizedProfit,quantity,fee,price,time,price_quantity
count,211277.000000,2.112770e+05,211277,211277,211277,211277,211277,211277,2.112770e+05,211277,211277,211277.000000,211277.000000,211277.000000,211277.000000,211277,211277.000000
unique,NaN,NaN,2,3,2,1,154,1,NaN,1,154,NaN,NaN,NaN,NaN,57220,NaN
top,NaN,NaN,True,BOTH,BUY,USDT,1000PEPEUSDT,USDT,NaN,USDT,1000PEPE,NaN,NaN,NaN,NaN,2024-06-20 11:07:50,NaN
freq,NaN,NaN,106080,78585,107292,211277,20574,211277,NaN,211277,20574,NaN,NaN,NaN,NaN,862,NaN
mean,105638.000000,3.964346e+18,NaN,NaN,NaN,NaN,NaN,NaN,1.090626e+04,NaN,NaN,3.270818,975.509483,-0.382787,4129.040315,NaN,975.509483
std,60990.560749,6.102597e+16,NaN,NaN,NaN,NaN,NaN,NaN,1.562781e+05,NaN,NaN,57.895095,4667.098916,1.793858,15363.534288,NaN,4667.098916
min,0.000000,3.672755e+18,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e-03,NaN,NaN,-3269.194444,0.006694,-120.458652,0.000158,NaN,0.006694
25%,52819.000000,3.942631e+18,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,NaN,NaN,0.000000,23.340915,-0.179868,0.143830,NaN,23.340915
50%,105638.000000,3.977117e+18,NaN,NaN,NaN,NaN,NaN,NaN,2.600000e+01,NaN,NaN,0.000000,127.775000,-0.051732,2.483300,NaN,127.775000
75%,158457.000000,4.011627e+18,NaN,NaN,NaN,NaN,NaN,NaN,5.790000e+02,NaN,NaN,0.577590,404.012000,-0.009454,44.621000,NaN,404.012000
max,211276.000000,4.041860e+18,NaN,NaN,NaN,NaN,NaN,NaN,2.100000e+07,NaN,NaN,8186.254058,602293.260000,0.000000,72105.000000,NaN,602293.260000

In [14]:
column_stats = df['realizedProfit'].describe()

# Display the statistics
print(column_stats)

count    211277.000000
mean          3.270818
std          57.895095
min       -3269.194444
25%           0.000000
50%           0.000000
75%           0.577590
max        8186.254058
Name: realizedProfit, dtype: float64

In [15]:
column_stats = df['quantity'].describe()

# Display the statistics
print(column_stats)

count    211277.000000
mean        975.509483
std        4667.098916
min           0.006694
25%          23.340915
50%         127.775000
75%         404.012000
max      602293.260000
Name: quantity, dtype: float64

In [16]:
column_stats = df['fee'].describe()

# Display the statistics
print(column_stats)

count    211277.000000
mean         -0.382787
std           1.793858
min        -120.458652
25%          -0.179868
50%          -0.051732
75%          -0.009454
max           0.000000
Name: fee, dtype: float64

In [17]:
column_stats = df['price'].describe()

# Display the statistics
print(column_stats)

count    211277.000000
mean       4129.040315
std       15363.534288
min           0.000158
25%           0.143830
50%           2.483300
75%          44.621000
max       72105.000000
Name: price, dtype: float64

In [18]:

column_stats = df['price_quantity'].describe()

# Display the statistics
print(column_stats)

count    211277.000000
mean        975.509483
std        4667.098916
min           0.006694
25%          23.340915
50%         127.775000
75%         404.012000
max      602293.260000
Name: price_quantity, dtype: float64